clear all
cap log close
local _logdate = subinstr("$S_DATE", " ", "", .)
log using "$log/assess_02_agreement_${run_tag}_`_logdate'.log", replace text

* assess_02_agreement.do -- measure how far the HC and Leiden partitions of the same run agree (NMI, ARI, AMI, share of units with identical harmonized IDs).
* Called by: _master.do (assess phase, do_assess switch).
* Reads:  includes _inc/compare_partitions.do; $temp/final_assignments_<run_tag>_<lvl>.dta
* Writes: $tables/agreement_<run_tag>.dta; $tables/agreement_<run_tag>.csv; $tables/agreement_baseline.tex (baseline run only)
* Notes:  We report ARI and AMI alongside NMI because NMI is not chance-corrected and rises mechanically with the number of clusters. The exact-match share is meaningful only because cluster_06_harmonize.do relabels the Leiden partition onto the HC labels.

include "$program/_inc/compare_partitions.do"

tempfile _agree_acc

foreach lvl of global levels {

    display as text _n "{hline 70}"
    display as text "===== assess_02 LEVEL: `lvl' ====="
    display as text "{hline 70}"

    use geoid hc_cluster leiden_cluster ///
        using "$temp/final_assignments_${run_tag}_`lvl'.dta", clear

    compare_partitions, a(hc_cluster) b(leiden_cluster)

    clear
    set obs 1
    gen str6   geo_level = "`lvl'"
    gen long   n_units   = `r(N)'
    gen double MI        = `r(MI)'
    gen double NMI       = `r(NMI)'
    gen double NMI_geom  = `r(NMI_geom)'
    gen double ARI       = `r(ARI)'
    gen double AMI       = `r(AMI)'

    gen double pct_exact = `r(pct_stable)'

    label variable geo_level "Geography (tract or county)"
    label variable n_units   "Units compared"
    label variable MI        "Mutual information"
    label variable NMI       "Normalized MI (arithmetic; NOT chance-corrected)"
    label variable NMI_geom  "Normalized MI (geometric)"
    label variable ARI       "Adjusted Rand index (chance-corrected)"
    label variable AMI       "Adjusted mutual information (chance-corrected)"
    label variable pct_exact "% units with identical harmonized cluster ID"

    format MI NMI NMI_geom ARI AMI %7.4f
    format pct_exact %5.1f

    display as text _n "{hline 50}"
    display as text "HC vs. Leiden agreement (`lvl')"
    display as text "{hline 50}"
    list, noobs

    capture confirm file "`_agree_acc'"
    if !_rc append using "`_agree_acc'"
    save "`_agree_acc'", replace
}

use "`_agree_acc'", clear
gen byte _ord = cond(geo_level == "tract", 1, 2)
sort _ord
drop _ord
save           "$tables/agreement_${run_tag}.dta", replace
export delimited using "$tables/agreement_${run_tag}.csv", replace
display as result "  -> $tables/agreement_${run_tag}.{csv,dta}"

if "${run_tag}" == "baseline" {
    capture file close _tex
    file open _tex using "$tables/agreement_baseline.tex", write replace
    file write _tex "% Auto-generated by assess_02_agreement.do; do not edit by hand." _n
    file write _tex "\begin{tabular}{lrrrr}" _n
    file write _tex "\toprule" _n
    file write _tex "Geography & \(n_{\text{units}}\) & NMI & ARI & \% exact-match \\" _n
    file write _tex "\midrule" _n
    local _N = _N
    forvalues r = 1/`_N' {
        local geo = strproper(geo_level[`r'])
        local nu  : display %9.0fc n_units[`r']
        local nu  = subinstr(trim("`nu'"), ",", "{,}", .)
        local nmi : display %5.3f NMI[`r']
        local ari : display %5.3f ARI[`r']
        local pe  : display %4.1f pct_exact[`r']
        file write _tex "`geo' & `nu' & `=trim("`nmi'")' & `=trim("`ari'")' & `=trim("`pe'")' \\" _n
    }
    file write _tex "\bottomrule" _n
    file write _tex "\end{tabular}" _n
    file close _tex
    display as result "  -> agreement_baseline.tex (LaTeX fragment for tab:agreement_hc_leiden)"
}
else display as text "tex skipped: run_tag=${run_tag} != baseline"

display as result _n "assess_02 done for tract and county."

cap log close
