clear all
cap log close
local _logdate = subinstr("$S_DATE", " ", "", .)
log using "$log/assess_08_partition_quality_alpha_${run_tag}_`_logdate'.log", replace text

* assess_08_partition_quality_alpha.do -- recluster each geography along the alpha grid (0 to 1 by 0.05) and record self-containment, modularity, silhouette and within-cluster D at every point.
* Called by: _master.do (assess phase, do_assess switch).
* Reads:  includes _inc/calib_params.do; $temp/division_lookup[_county].dta; $temp/pflow_<lvl>_<period_pflow_suffix>.dta; shell "$py" _py/partition_quality_alpha.py
* Writes: $tables/partition_quality_alpha_<run_tag>.dta; $tables/partition_quality_alpha_<run_tag>.csv; $tables/partition_quality_alpha.tex (baseline run only)
* Notes:  The sweep holds cap_km, k and the Leiden resolution at the constants in _inc/calib_params.do, not at the values in chosen_params_<lvl>.dta. It therefore checks the calibration constants rather than rerunning the pipeline. The grid comes from $alpha_sc_grid when _master.do sets it.

local pyalpha "$program/_py/partition_quality_alpha.py"
capture confirm file "`pyalpha'"
if _rc {
    di as error "Missing `pyalpha'; cannot run the alpha sweep."
    exit 198
}

include "$program/_inc/calib_params.do"

local alpha_grid "$alpha_sc_grid"
if "`alpha_grid'" == "" {
    numlist "0(0.05)1"
    local alpha_grid "`r(numlist)'"
}
local alpha_csv : subinstr local alpha_grid " " ",", all

tempfile _acc
local _have 0

foreach lvl of global levels {

    display as text _n "{hline 70}"
    display as text "===== assess_08 LEVEL: `lvl' ====="
    display as text "{hline 70}"

    if "`lvl'" == "tract" {
        local divlookup "$temp/division_lookup.dta"
    }
    else {
        local divlookup "$temp/division_lookup_county.dta"
    }
    local pflow "$temp/pflow_`lvl'_${period_pflow_suffix}.dta"
    local cap_km = ``lvl'_cap_km'
    local k_nat  = ``lvl'_hc_k_national'
    local res    = ``lvl'_leiden_res'

    capture confirm file "`divlookup'"
    if _rc {
        display as error "Missing `divlookup'; skipping `lvl'."
        continue
    }
    capture confirm file "`pflow'"
    if _rc {
        display as error "Missing `pflow'; skipping `lvl'."
        continue
    }

    tempfile out_t
    local out_csv "`out_t'.csv"

    display as text "alpha grid: `alpha_grid'  (cap=`cap_km' k_nat=`k_nat')"
    display as text "  running partition_quality_alpha.py for `lvl' ..."
    shell "$py" "`pyalpha'" "`lvl'" "`divlookup'" "`pflow'" ///
        "`cap_km'" "`k_nat'" "`res'" "$seed" "`alpha_csv'" "`out_csv'"

    capture confirm file "`out_csv'"
    if _rc {
        display as error "  no output for `lvl'."
        continue
    }
    import delimited using "`out_csv'", varnames(1) clear
    if `_have' append using "`_acc'"
    save "`_acc'", replace
    local _have 1
}

capture confirm file "`_acc'"
if _rc {
    display as error "No partition-quality-vs-alpha metrics produced."
    cap log close
    exit 0
}

use "`_acc'", clear
gen byte _ordg = cond(geo_level == "tract", 1, 2)
sort _ordg alpha
drop _ordg

label variable geo_level        "Geography (tract or county)"
label variable alpha            "Flow weight alpha"
label variable self_containment "Within-cluster share of commuting flow (selector)"
label variable modularity       "Newman modularity on the similarity graph"
label variable silhouette       "Mean silhouette width (on D; descriptive)"
label variable within_d         "Mean within-cluster D (compactness; descriptive)"
label variable n_clusters       "Total clusters across divisions"
format self_containment modularity silhouette within_d %6.4f

save           "$tables/partition_quality_alpha_${run_tag}.dta", replace
export delimited using "$tables/partition_quality_alpha_${run_tag}.csv", replace
display as result "  -> $tables/partition_quality_alpha_${run_tag}.{csv,dta}"

list geo_level alpha self_containment modularity silhouette within_d, ///
    noobs sepby(geo_level)

if "${run_tag}" == "baseline" {
    capture file close _tex
    file open _tex using "$tables/partition_quality_alpha.tex", write replace
    file write _tex "% Auto-generated by assess_08_partition_quality_alpha.do; do not edit by hand." _n
    file write _tex "\begin{tabular}{lrrrr}" _n
    file write _tex "\toprule" _n
    file write _tex "\(\alpha\) & Self-cont. & Modularity & Silhouette & Within \(D\) \\" _n

    foreach lvl in Tract County {
        local lvlc = lower("`lvl'")
        if strpos(" ${levels} ", " `lvlc' ") == 0 continue
        quietly count if geo_level == "`lvlc'"
        if r(N) == 0 continue
        local chosen = ``lvlc'_alpha'
        file write _tex "\midrule" _n
        file write _tex "\multicolumn{5}{l}{\textit{`lvl' (cap \(\bar d=" ///
            (``lvlc'_cap_km') "\) km; chosen \(\alpha=" %4.2f (`chosen') "\))}} \\" _n
        preserve
        keep if geo_level == "`lvlc'"
        sort alpha
        forvalues r = 1/`=_N' {
            local a   : display %4.2f alpha[`r']
            local sc  : display %5.3f self_containment[`r']
            local mo  : display %5.3f modularity[`r']
            local si  : display %6.3f silhouette[`r']
            local wd  : display %5.3f within_d[`r']
            if abs(alpha[`r'] - `chosen') < 1e-6 {
                file write _tex "\textbf{`=trim("`a'")'} & \textbf{`=trim("`sc'")'} & `=trim("`mo'")' & `=trim("`si'")' & `=trim("`wd'")' \\" _n
            }
            else {
                file write _tex "`=trim("`a'")' & `=trim("`sc'")' & `=trim("`mo'")' & `=trim("`si'")' & `=trim("`wd'")' \\" _n
            }
        }
        restore
    }
    file write _tex "\bottomrule" _n
    file write _tex "\end{tabular}" _n
    file close _tex
    display as result "  -> partition_quality_alpha.tex (LaTeX fragment for tab:partition_quality_alpha)"
}

display as result _n "assess_08 done."
cap log close
