clear all
cap log close
local _logdate = subinstr("$S_DATE", " ", "", .)
log using "$log/report_02_dissim_example_${run_tag}_`_logdate'.log", replace text

* report_02_dissim_example.do -- extract the pairwise dissimilarity matrix for a small set of named tracts and counties in Champaign County, IL as the paper's worked example.
* Called by: _master.do (generate phase, do_generate switch).
* Reads:  includes _inc/ensure_county_div_lookup.do; $temp/division_lookup[_county].dta; $hc_input/<lvl>_<run_tag>/dissim_div<div>.csv
* Writes: $tables/dissim_example_<lvl>.dta, .csv and .tex
* Notes:  Dissimilarities exist only within a division. When the example units straddle divisions we keep the division that holds most of them and warn that the table is smaller than described. The LaTeX table prints the lower triangle only.

local tract_example_geoids ///
    17019005400 17019005500 17019005600 17019005700 ///
    17019005800 17019005900 17019006000 17019006100

local county_example_geoids ///
    17019 17041 17053 17105 17107 17125 17139 17147

capture confirm file "$temp/division_lookup_county.dta"
local _have_lookup = !_rc
capture confirm file "$temp/centroids_county.dta"
local _have_cent = !_rc
if `_have_lookup' | `_have_cent' {
    include "$program/_inc/ensure_county_div_lookup.do"
}

foreach lvl of global levels {

    display as text _n "{hline 70}"
    display as text "===== report_02 LEVEL: `lvl' ====="
    display as text "{hline 70}"

    if "`lvl'" == "tract" {
        local divlookup "$temp/division_lookup.dta"
        local example_geoids "`tract_example_geoids'"
    }
    else {
        local divlookup "$temp/division_lookup_county.dta"
        local example_geoids "`county_example_geoids'"
    }

    local n_ex : word count `example_geoids'
    display as text "Example unit count (`lvl'): `n_ex'"

    capture confirm file "`divlookup'"
    if _rc {
        display as text "report_02: `divlookup' not found; skipping level `lvl'."
        continue
    }
    use geoid div_id using "`divlookup'", clear
    gen byte _hit = 0
    foreach g of local example_geoids {
        quietly replace _hit = 1 if geoid == "`g'"
    }
    keep if _hit == 1

    quietly count
    if r(N) == 0 {
        di as error "No example units matched in `divlookup'; edit the GEOID list. Skipping `lvl'."
        continue
    }
    if r(N) < `n_ex' {
        di as error "WARNING (report_02, `lvl'): only " r(N) " of the `n_ex' documented example GEOIDs were found in `divlookup'; the worked-example table will be smaller than the manuscript describes. Check the GEOID list at the top of this script."
    }

    quietly levelsof div_id, local(divs)
    local n_divs : word count `divs'

    bysort div_id: gen long _ndiv_count = _N
    gsort -_ndiv_count div_id
    local div_id    = div_id[1]
    local n_in_div  = _ndiv_count[1]
    display as text "Example units span `n_divs' division(s); using div `div_id' (`n_in_div' of `: word count `example_geoids'' units)."

    keep if div_id == `div_id'
    quietly levelsof geoid, local(example_geoids) clean
    drop _ndiv_count _hit

    local fname = string(`div_id', "$divfmt")
    local dissim "$hc_input/`lvl'_${run_tag}/dissim_div`fname'.csv"
    capture confirm file "`dissim'"
    if _rc {
        display as text "report_02: missing dissim CSV for div `div_id' (`lvl'): `dissim'; skipping level."
        continue
    }

    import delimited using "`dissim'", varnames(1) stringcols(1 2) clear
    keep geo_i geo_j d

    gen byte keep_i = 0
    gen byte keep_j = 0
    foreach g of local example_geoids {
        quietly replace keep_i = 1 if geo_i == "`g'"
        quietly replace keep_j = 1 if geo_j == "`g'"
    }
    keep if keep_i == 1 & keep_j == 1
    drop keep_i keep_j

    preserve
    keep geo_i
    duplicates drop
    rename geo_i geoid
    gen geo_i = geoid
    gen geo_j = geoid
    gen double d = 0
    keep geo_i geo_j d
    tempfile diag
    save `diag'
    restore

    append using `diag'

    preserve
    rename (geo_i geo_j) (geo_j geo_i)
    tempfile upper
    save `upper'
    restore
    append using `upper'

    duplicates drop geo_i geo_j, force

    keep geo_i geo_j d
    reshape wide d, i(geo_i) j(geo_j) string

    sort geo_i
    order geo_i
    format d* %5.3f

    save "$tables/dissim_example_`lvl'.dta", replace
    export delimited using "$tables/dissim_example_`lvl'.csv", replace

    display as text _n "Dissimilarity example (`lvl', rows=geo_i, cols=geo_j):"
    list, noobs

    quietly levelsof geo_i, local(_order) clean
    local _R : word count `_order'
    capture file close _tex
    file open _tex using "$tables/dissim_example_`lvl'.tex", write replace
    local _colspec "l"
    forvalues c = 1/`_R' {
        local _colspec "`_colspec'r"
    }
    file write _tex "% Auto-generated by report_02_dissim_example.do; do not edit by hand." _n
    file write _tex "\begin{tabular}{`_colspec'}" _n
    file write _tex "\toprule" _n
    local _hdr ""
    forvalues c = 1/`_R' {
        local _gc : word `c' of `_order'
        if "`lvl'" == "tract" local _lab = substr("`_gc'", -4, 4)
        else                  local _lab "`_gc'"
        local _hdr "`_hdr' & `_lab'"
    }
    file write _tex "`_hdr' \\" _n
    file write _tex "\midrule" _n
    forvalues r = 1/`_R' {
        local _gr : word `r' of `_order'
        if "`lvl'" == "tract" local _rlab = substr("`_gr'", -4, 4)
        else                  local _rlab "`_gr'"
        local _line "`_rlab'"
        forvalues c = 1/`_R' {
            if `c' <= `r' {
                local _gc : word `c' of `_order'
                local _v  = d`_gc'[`r']
                local _vs : display %5.3f `_v'
                local _line "`_line' & `_vs'"
            }
            else {
                local _line "`_line' &"
            }
        }
        file write _tex "`_line' \\" _n
    }
    file write _tex "\bottomrule" _n
    file write _tex "\end{tabular}" _n
    file close _tex
    display as result "  -> dissim_example_`lvl'.tex (LaTeX fragment)"

    display as result "report_02 (`lvl') done."
}

display as result _n "report_02 done.  Edit the GEOID lists at the top for paper-specific units."

cap log close
