* booktabs.do -- defines bt_open, bt_row, bt_num, bt_close and tex_escape, the helpers that write booktabs tabular fragments for the manuscript.
* Included by: gen/tab_*.do (twelve table scripts) and report/report_01_descriptive_table.do.
* Expects: the handle(), path() and colspec() each caller passes to bt_open.
* Writes: the LaTeX file named in bt_open's path() (a tabular fragment, not a floating table).
* Notes:  bt_num wraps each thousands separator in braces so it typesets without the math-mode space after a comma; tex_escape covers &, %, #, _ and $ only.

capture program drop bt_open
program define bt_open
    syntax , handle(name) path(string) colspec(string) script(string)
    capture file close `handle'
    file open `handle' using "`path'", write replace
    file write `handle' "% Auto-generated by `script'; do not edit by hand." _n
    file write `handle' "\begin{tabular}{`colspec'}" _n
    file write `handle' "\toprule" _n
end

capture program drop bt_num
program define bt_num, rclass
    syntax , value(string) fmt(string) [bold dagger]
    local s : display `fmt' (`value')
    local s = trim("`s'")
    local s = subinstr("`s'", ",", "{,}", .)
    if "`bold'"   != "" local s "\textbf{`s'}"
    if "`dagger'" != "" local s "`s'\,$^\dagger$"
    return local s `"`s'"'
end

capture program drop bt_row
program define bt_row
    syntax , handle(name) cells(string asis)

    local rest `"`macval(cells)'"'
    gettoken rest : rest

    local line ""
    local sep ""
    while trim(`"`macval(rest)'"') != "" {
        gettoken c rest : rest
        local line `"`macval(line)'`sep'`macval(c)'"'
        local sep " & "
    }

    file write `handle' `"`macval(line)' \\"' _n
end

capture program drop bt_close
program define bt_close
    syntax , handle(name)
    file write `handle' "\bottomrule" _n
    file write `handle' "\end{tabular}" _n
    file close `handle'
end

capture program drop tex_escape
program define tex_escape, rclass
    syntax , s(string asis)
    local out `"`s'"'
    local out = subinstr(`"`out'"', "&", "\&", .)
    local out = subinstr(`"`out'"', "%", "\%", .)
    local out = subinstr(`"`out'"', "#", "\#", .)
    local out = subinstr(`"`out'"', "_", "\_", .)
    local out = subinstr(`"`out'"', char(36), char(92) + char(36), .)
    return local s `"`out'"'
end
